Remove custom management for Java heap sizes
linuxserver/docker-unifi-controller pull request #90
Opened 2021-09-05 11:38 UTC by ferferga

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

 - [X] I have read the [contributing](https://github.com/linuxserver/docker-unifi-controller/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

## Description / Benefits of this PR and context:
Unifi Controller already handles the ``xms`` and ``xmx`` values on it's own [by using the ``system.properties`` file](https://web.archive.org/web/20201004125720/https://help.ui.com/hc/en-us/articles/115005159588-UniFi-How-to-Tune-the-Controller-for-High-Number-of-UniFi-Devices). Users that want to have different values for the Java allocator should use ``unifi.xmx`` and ``unifi.xms`` keys in the ``system.properties`` instead. 

Our own override of the values in the Java arguments is confusing, because what if someone else have configured one value in the environment variable but a different one in system.properties? Which one takes precedence over which? There's no official documentation (beside Java's own docs) about the CLI parameters, so it might be causing conflicts within Unifi Controller itself.

It's also unclear wether Unifi Controller is using the values we're providing in CLI instead of the values present in ``system.properties``. Also, Ubiquiti might change the defaults in new versions without further notice, which may cause incompatibilities with our own values, making this container prone to breaking and headaches in the future.

## How Has This Been Tested?
Changing the ``unifi.xms`` parameter in ``system.properties`` does indeed reduce the initial memory allocation, as of Unifi Controller 6.2.26

## Source / References:
* [Unifi docs](https://web.archive.org/web/20201004125720/https://help.ui.com/hc/en-us/articles/115005159588-UniFi-How-to-Tune-the-Controller-for-High-Number-of-UniFi-Devices)

2021-10-06 05:41 UTC, ferferga commented
Bump

2021-11-07 09:30 UTC, ferferga commented
Bump

2021-12-08 09:41 UTC, ferferga commented
Bump

2021-12-21 23:01 UTC, drizuid commented
seems like a valid concern: with the defaults being set in the properties file to 1GB setting below that would likely cause starvation and setting above would have no affect at all. 
i dont see unifi.xmx or unifi.xms in a default build, so we could take those envvars and rather than putting them into the java run command, echo them into the system.properties

lets discuss at some point (note, our backlog is large, you bumping things doesn't do anything at all other than let the bot mark it stale more than once) We will get to it when we get to it.

2021-12-23 10:32 UTC, ferferga commented
I expected that :)

However, if I don't comment "bump" from time to time, the bot would close this PR :(.

2021-12-23 14:27 UTC, drizuid commented
@linuxserver/development assuming system.properties isn't generated until after deployment completes (or maybe even first login/initial setup) I dont see a lot of room to properly support this. I had thought to change our envar to cat the changes into the system.properties since these settings aren't there by default, but with the lack of file existence that doesnt seem possible. It may be best to simply remove the envvars all together for now. To be fair, we have one user that likely even understands what this does and he's the one who opened the issue :D

2021-12-23 14:34 UTC, drizuid requested changes
please add changelog entry on readme-vars

2021-12-23 14:34 UTC, drizuid commented on readme-vars.yml
> -opt_param_usage_include_env: true
set to false and leave in

2021-12-23 14:34 UTC, drizuid commented on readme-vars.yml
> -opt_param_env_vars:
leave this in, without the vars below

2021-12-23 14:34 UTC, drizuid commented
you'll need to resolve the branch conflict on readme too

2021-12-24 18:54 UTC, drizuid commented
After some internal debate, we've determined that simply removing this would cause too many issues for arm users with less than 1G of ram. Due to this, we've heavily tested a commit internally which addresses both your concern and ours for low mem users. 
You can see the PR here: https://github.com/linuxserver/docker-unifi-controller/pull/119  

Even though we won't be using your PR, i want to thank you for bringing this to our attention!

2021-12-24 18:54 UTC, closed without merging

2021-12-24 19:43 UTC, ferferga commented
@drizuid Thank you very much! As soon as the situation improves it's fine for me :)

That PR looks really good! :)